### ISSUE TITLE
`pybritive checkout` lacks region support

### ISSUE THREAD

**Issue by michaelbrewer** [britive/python-cli#139]
Currently the britive cli, installed via NPM, is going away and replaced with `pybritive` and one of the features missing it setting the region to checkout:

```bash
britive checkout -r ${region} -a ${profileName} ${britiveName} -s
```

It is an AWS only feature, but it required for our automation scripts

`-r, --region=region                Specify region for checkout (AWS only)` 

This is not support by `pybritive`

```bash
pybritive checkout -m integrate -a ${profileName} ${britiveName}
```

**Comment by twratl** [comment]
Hi @michaelbrewer. Thanks for your feedback on this item. AWS credentials are not bound to a region so what behavior would you like to see with the `--region/-r` flag? Adding an `AWS_DEFAULT_REGION` environment variable when using the `--mode env` option? Or something else?

**Comment by michaelbrewer** [comment]
Yes. It's about the config files of produces. So that when people use these credentials the defaults for that profile has been set. 

So I was hoping for minimal changes from the old version. But if it is not in scope. We can create config for the requested region
