### ISSUE TITLE
`pybritive configure` do not support setting the proxy

### ISSUE THREAD

**Issue by michaelbrewer** [britive/python-cli#140]
Relates to migration from britive cli to pybritive and loss of functionality (See #139 )

When configuring a corp. proxy, the old britive cli allows for this

```bash
britive configure --tenant_domain=MY_TENANT_ID.britive-app.com --proxy=http://MY_CORT_PORXY:8080
```

Migration also does not work with `pybritive configure import`

**Comment by twratl** [comment]
`pybritive` can be configured to use a proxy via the same methods as the python SDK for Britive. Details [here](https://github.com/britive/python-sdk?tab=readme-ov-file#proxies). It is using the standard proxy environment variables for python `requests` library.

**Comment by michaelbrewer** [comment]
Ok. Will try that. Proxy is only required for part of the options. So using environment variables would need to be wrapped around the command. 

Legacy cli allowed for this to just happen for a specific command.
