### ISSUE TITLE
Interactive login doesn't use the specified browser for applicable commands.

### ISSUE THREAD

**Issue by fiservwillb** [britive/python-cli#92]
Example:

```bash
pybritive checkout AWS_Application/10987654321/10987654321_rolename -m browser-safari
```

Will open in the OS defined default browser still.

Same for:

```bash
pybritive aws console --profile 10987654321_rolename --browser safari
```

Proposed option to fix this submitted in #91

**Comment by twratl** [comment]
This fix has been incorporated into `pip install pybritive==1.5.0rc2`. It will remain a release candidate until a full QA test can be run against this new version.
